### ISSUE TITLE
Ladders v1

### ISSUE THREAD

**Issue by alex-kozlov** [teamladders/prototype#6]
Ladder is one of the fundamental pillars of the application.

We can start with the simplest scenarios: 

- [ ] Any user can create a new Ladder.
- [ ] Any user can view and edit the list of the Ladders he created.
- [ ] The other users should be able to view the list of available Ladders.
- [ ] Any user can register for available Ladder.
